# Generated by Django 5.1.15 on 2026-03-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
